apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivanassis-song-recommender-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ivanassis-song-recommender
  template:
    metadata:
      labels:
        app: ivanassis-song-recommender
    spec:
      containers:
      - name: frontend
        image: quay.io/ivan_assis/frontend:0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 52033
        env:
        - name: APP_VERSION
          value: "1.0.2"
        volumeMounts:
        - name: shared-volume
          mountPath: /app/shared
      - name: model
        image: quay.io/ivan_assis/model:0.4
        imagePullPolicy: Always
        env:
        - name: DATASET_URL
          value: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds2.csv"
        volumeMounts:
        - name: shared-volume
          mountPath: /app/shared
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: project2-pvc-ivanassis